# Generated by Django 5.2.4 on 2025-07-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyrox', '0005_userprofile_id_alter_otp_user_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
