# Generated by Django 5.2.4 on 2025-07-25 09:16

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('bio', models.TextField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('preferred_workout', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('running', 'Running'), ('strength', 'Strength Training'), ('yoga', 'Yoga'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('hiit', 'HIIT'), ('other', 'Other')], max_length=49)),
                ('preferred_language', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('hi', 'Hindi'), ('other', 'Other')], max_length=20)),
                ('available_days', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=27)),
                ('training_time', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=25)),
                ('looking_for', models.CharField(blank=True, choices=[('partner', 'Workout Partner'), ('trainer', 'Trainer'), ('group', 'Group')], max_length=20)),
                ('partner_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('running', models.PositiveIntegerField(blank=True, null=True)),
                ('gym', models.BooleanField(default=False)),
                ('cycling', models.PositiveIntegerField(blank=True, null=True)),
                ('sports', models.TextField(blank=True, max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('area', models.PositiveIntegerField(blank=True, null=True)),
                ('partner_age', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hyroxinfit.profile')),
            ],
        ),
    ]
